document.writeln("");
document.writeln("<div style=\"position: absolute; bottom: 0; left : 20%\" id=\"ftConw\">");
document.writeln("	<HR style=\"FILTER: alpha(opacity = 100, finishopacity = 0, style = 1)\"");
document.writeln("	width=\"100%\" color=#987cb9 SIZE=3>");
document.writeln("	<p>");
document.writeln("		<a style=\"text-align: center;\" target=\"_blank\" href=\"\"></a> <b><font");
document.writeln("			face=\"Comic Sans MS\" style=\"font-size: 18px;\">We do not");
document.writeln("				inherit the earth from our ancestors. We borrow it from our");
document.writeln("				children.</font></b>");
document.writeln("	</p>");
document.writeln("	<p style=\"text-align: center;\" id=\"cp\">");
document.writeln("		&copy;2016&nbsp;Website&nbsp; <a href=\"\">README</a>&nbsp; <a");
document.writeln("			class=\"cp-feedback\" href=\"\">FeedBack</a>&nbsp; 032112302&nbsp; <i");
document.writeln("			class=\"c-icon-icrlogo\"></i>");
document.writeln("	</p>");
document.writeln("</div>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");