document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />");
document.writeln("<title>Shopping</title>");
document.writeln("<link rel=\"stylesheet\" type=\"text/css\"");
document.writeln("	href=\"//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css\">");
document.writeln("<script src=\"js/jquery.min.js\"></script>");
document.writeln("<script src=\"js/bootstrap.min.js\"></script>");
document.writeln("<style>");
document.writeln(".container {");
document.writeln("	position: relative;");
document.writeln("	text-align: center;");
document.writeln("}");
document.writeln("");
document.writeln(".center {");
document.writeln("	position: absolute;");
document.writeln("	font-size: 18px;");
document.writeln("	left: 0%;");
document.writeln("	top: 50%;");
document.writeln("	width: 100%;");
document.writeln("}");
document.writeln("");
document.writeln(".topright {");
document.writeln("	position: absolute;");
document.writeln("	font-size: 18px;");
document.writeln("	top: 8px;");
document.writeln("	right: 16px;");
document.writeln("}");
document.writeln("");
document.writeln("img {");
document.writeln("	width: 100%;");
document.writeln("	height: 80%;");
document.writeln("	opacity: 0.3;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("	<div style=\"background-color: white; width: 100%; padding: 10px;\">");
document.writeln("		<table>");
document.writeln("			<tr>");
document.writeln("				<font face=\"Comic Sans MS\" style=\"font-size: 23px;\">");
document.writeln("					<center>");
document.writeln("						<p>Second-Hand Market</p>");
document.writeln("					</center>");
document.writeln("				</font>");
document.writeln("			</tr>");
document.writeln("			<tr>");
document.writeln("			<div style=\"float:left;width:50%;overflow:hidden;height:44px;background-color: lightblue;\">");
document.writeln("			<input  onclick=\"window.location.href=\'adminLog.jsp\'\" type=\"image\" src=\"graph/头像.png\"  style=\" align: left; width: 50px; height: 50px;\" />");
document.writeln("							");
document.writeln("			</div>");
document.writeln("				<div style=\"float:right ;width:50%;overflow:hidden;height:44px;background-color: lightblue;\">");
document.writeln("					<font face=\"Comic Sans MS\" style=\"font-size: 15px;\"> <b><a");
document.writeln("							onclick=\"http://localhost:8080/FinalYear/AdminUserManager.jsp\">Account</a>&nbsp; <a href=\"\">ManagerAccount</a>&nbsp; <a");
document.writeln("							href=\"\">ShoppingCart</a>&nbsp; <a href=\"\">Favorite</a>&nbsp; <a");
document.writeln("							href=\"\">Category</a>&nbsp; <a href=\"\">Messages</a>&nbsp; <a");
document.writeln("							href=\"\">Navigation</a>&nbsp; <a href=\"\">更多»</a></b>");
document.writeln("					</font>");
document.writeln("				</div>");
document.writeln("			</tr>");
document.writeln("		</table>");
document.writeln("	</div>");